# Change these first
owner: atiniguar # Your GitHub organization or username, where this repository lives
repo: atiniguar.github.io # The name of this repository
user-agent: atiniguar
sites: 
  - name: PortalKits
    url: https://portalkits.celtech.com.gt
  - name: Pretups
    url: https://pretups.celtech.com.gt
  - name: Auth
    url: https://auth.celtech.com.gt
    method: GET
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 302
      - 308
    maxResponseTime: 5000
    __dangerous__insecure: true

  - name: Auth API
    url: https://auth.celtech.com.gt/v1
    __dangerous__insecure: true
  - name: wttx
    url: https://wttx.celtech.com.gt
    method: GET
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 302
      - 308
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: Shortener API (GO)
    url: https://go.celtech.com.gt
    method: GET
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 302
      - 308
    maxResponseTime: 5000
    __dangerous__insecure: true    
  - name: Shortener Dashboard
    url: https://shortenerdash.celtech.com.gt
    method: GET
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 302
      - 308
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: Altoque
    url: http://altoque.celtech.com.gt:8080/index.xhtml
    __dangerous__insecure: true
  - name: FEL
    url: https://fel.celtech.com.gt/index.jsp
    __dangerous__insecure: true
  
assignees:
- atiniguar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  #baseUrl: /atiniguar.github.io
  #baseUrl: atiniguar.github.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Celtech Status
  introTitle: "**Celtech Status** Es un monitor de Estados de nuestros servicios en tiempo real."
  introMessage: Con la ayuda de esta herramienta podemos verificar cada portal en **Tiempo Real** y detectar incovenientes.  [**Esta herramienta esta impulsado por GitHub y Upptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Ver Estado
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
